/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import { Injectable } from '@nestjs/common';
import * as puppeteer from 'puppeteer';
import { Response } from 'express';

@Injectable()
export class PaymentReceiptPDFService {
  async generatePDF(payment: any, res: Response) {
    let browser;

    try {
      const paymentDate = payment?.paymentDate
        ? new Date(payment.paymentDate).toISOString().split('T')[0]
        : '-';

      const html = `
      <html>
        <head>
          <style>
            body {
              font-family: Arial, sans-serif;
              margin: 25px;
              color: #111827;
              background: #fff;
            }

            /* HEADER */
            .header {
              text-align: center;
              background: linear-gradient(135deg, #1d4ed8, #2563eb);
              color: white;
              padding: 18px;
              border-radius: 8px;
              margin-bottom: 20px;
            }

            .header h1 {
              margin: 0;
              font-size: 22px;
              letter-spacing: 1px;
            }

            .sub-header {
              font-size: 12px;
              margin-top: 6px;
              opacity: 0.9;
            }

            /* SECTION BOX */
            .box {
              border: 1px solid #e5e7eb;
              border-radius: 8px;
              padding: 14px;
              margin-bottom: 14px;
              background: #f9fafb;
            }

            .title {
              font-weight: bold;
              font-size: 13px;
              margin-bottom: 10px;
              padding-bottom: 6px;
              border-bottom: 2px solid #2563eb;
              color: #1f2937;
            }

            .row {
              display: flex;
              justify-content: space-between;
              margin-bottom: 6px;
              font-size: 13px;
            }

            b {
              color: #111827;
            }

            /* TABLE */
            table {
              width: 100%;
              border-collapse: collapse;
              font-size: 12px;
              margin-top: 10px;
              border-radius: 6px;
              overflow: hidden;
            }

            th {
              background: #2563eb;
              color: white;
              padding: 10px;
              text-align: center;
              font-size: 12px;
            }

            td {
              border-bottom: 1px solid #e5e7eb;
              padding: 8px;
              text-align: center;
              background: white;
            }

            tr:nth-child(even) td {
              background: #f9fafb;
            }

            /* TOTAL BOX */
            .total-box {
              margin-top: 12px;
              text-align: right;
              font-size: 16px;
              font-weight: bold;
              padding: 10px;
              background: #ecfdf5;
              border: 1px solid #10b981;
              border-radius: 6px;
              color: #065f46;
            }

            /* FOOTER */
            .footer {
              margin-top: 60px;
              display: flex;
              justify-content: space-between;
              font-size: 13px;
            }

            .sign {
              text-align: center;
              width: 30%;
            }

            .sign-line {
              margin-top: 45px;
              border-top: 1px solid #111827;
            }
          </style>
        </head>

        <body>

          <!-- HEADER -->
          <div class="header">
            <h1>FUND TRANSFER RECEIPT</h1>
            <div class="sub-header">
              Generated by Raddha System | Date: ${paymentDate}
            </div>
          </div>

          <!-- RECEIPT INFO -->
          <div class="box">
            <div class="title">Receipt Information</div>
            <div class="row">
              <span><b>Receipt No:</b> ${payment?.accountNo ?? '-'}</span>
              <span><b>Date:</b> ${paymentDate}</span>
            </div>
          </div>

          <!-- SUPPLIER -->
          <div class="box">
            <div class="title">Beneficiary Details</div>
            <div class="row"><span><b>Name:</b> ${payment?.supplier?.name ?? '-'}</span></div>
            <div class="row"><span><b>Phone:</b> ${payment?.supplier?.phone ?? '-'}</span></div>
            <div class="row"><span><b>Email:</b> ${payment?.supplier?.email ?? '-'}</span></div>
          </div>

          <!-- INVOICE -->
          <div class="box">
            <div class="title">Invoice Details</div>
            <div class="row"><span><b>Invoice No:</b> ${payment?.invoice?.invoiceNo ?? '-'}</span></div>
            <div class="row"><span><b>Invoice Total:</b> ${Number(payment?.invoice?.finalCost ?? 0).toFixed(2)}</span></div>
          </div>

          <!-- PAYMENT -->
          <div class="box">
            <div class="title">Payment Details</div>
            <div class="row"><span><b>Amount Paid:</b> ${Number(payment?.payment?.amount ?? 0).toFixed(2)}</span></div>
            <div class="row"><span><b>Mode:</b> ${payment?.payment?.mode ?? '-'}</span></div>
            <div class="row"><span><b>Status:</b> ${payment?.payment?.status ?? '-'}</span></div>
            <div class="row"><span><b>Description:</b> ${payment?.payment?.description ?? '-'}</span></div>
          </div>

          <!-- ITEMS TABLE -->
          <div class="box">
            <div class="title">Invoice Items</div>

            <table>
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Qty</th>
                  <th>Rate</th>
                  <th>Total</th>
                </tr>
              </thead>

              <tbody>
                ${
                  payment?.invoice?.details?.map((d: any) => `
                    <tr>
                      <td>${d.product ?? '-'}</td>
                      <td>${Number(d.quantity ?? 0)}</td>
                      <td>${Number(d.rate ?? 0).toFixed(2)}</td>
                      <td>${Number(d.total ?? 0).toFixed(2)}</td>
                    </tr>
                  `).join('') || `
                    <tr>
                      <td colspan="4">No items found</td>
                    </tr>
                  `
                }
              </tbody>
            </table>

            <div class="total-box">
              GRAND TOTAL: ${Number(payment?.invoice?.finalCost ?? 0).toFixed(2)}
            </div>
          </div>

          <!-- SIGNATURE -->
          <div class="footer">
            <div class="sign">
              <div class="sign-line"></div>
              Prepared By
            </div>

            <div class="sign">
              <div class="sign-line"></div>
              Approved By
            </div>

            <div class="sign">
              <div class="sign-line"></div>
              Authorized Signature
            </div>
          </div>

        </body>
      </html>
      `;

      browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      });

      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });

      const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: 20, bottom: 20 },
      });

      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader(
        'Content-Disposition',
        `inline; filename=FundTransfer-${payment?.accountNo}.pdf`,
      );

      res.send(pdf);

    } catch (error) {
      console.error('PDF Error:', error);
      res.status(500).json({ message: 'Failed to generate receipt' });

    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }
}